# .github/workflows/trigger-h2o-3-devops.yml
name: Trigger H2O-3 DevOps Workflows

permissions:
  contents: read

on:
  push:
    branches: [master, rel-3.46.0]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vulnerability Scan
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.H2O_3_DEVOPS_REPO_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/h2oai/h2o-3-devops/dispatches \
            -d '{"event_type":"h2o3-push","client_payload":{"branch":"${{ github.ref_name }}","sha":"${{ github.sha }}"}}'
