# .github/workflows/trigger-vulnerability-scan.yml
name: Trigger Vulnerability Scan

permissions:
  contents: read

on:
  push:
    branches: [master, rel-3.46.0]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vulnerability Scan
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.H2O_3_DEVOPS_REPO_TOKEN }}" \
            https://api.github.com/repos/h2oai/h2o-3-devops/dispatches \
            -d '{"event_type":"h2o3-push","client_payload":{"branch":"${{ github.ref_name }}","sha":"${{ github.sha }}"}}'
